name: CI (.NET Build)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest     # puede ser ubuntu-latest si prefieres

    steps:
    - name: Clonar código
      uses: actions/checkout@v3

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'    # o '7.0.x' si usas .NET 7

    - name: Restaurar dependencias
      run: dotnet restore appComercial.sln

    - name: Compilar solución
      run: dotnet build appComercial.sln --configuration Release --no-restore
